<?php
/**
 * AutoBase default Store switch languages template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''; ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id); ?>">
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id); ?>">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()); ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()); ?></span>
                </strong>
            </div>
            <div class="switcher-lang">
                <?php foreach ($block->getStores() as $_lang) : ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                        <strong class="view-<?= $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang); ?>'>
                                <?= $block->escapeHtml($_lang->getName()); ?>
                            </a>
                        </strong>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
