<?php
/**
 * AutoBase default Catalog Inventory stockqty default template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()) : ?>
    <div class="availability only">
        <span><?=__('Product ends'); ?></span>
    </div>
<?php endif ?>
