<?php
/**
 * AutoBase default Catalog product view attribute template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$_shown_items = 2;

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue) : ?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className); ?>">
    <?php if ($renderLabel) : ?>
        <strong class="type"><?= $block->escapeHtml($_attributeLabel); ?></strong>
    <?php endif; ?>
    <div class="value drop-out-js" <?= /* @noEscape */ $_attributeAddAttribute; ?>><?= /* @noEscape */ $_attributeValue; ?></div>
    <?php if($block->escapeHtmlAttr($_className) === 'description') : ?>
        <a href="#" class="show-trigger show-js" data-mage-init='{"showHideList":
            {
                "position":"<?= $_shown_items; ?>",
                "childElement":"p",
                "effect":"show"
            }}'>
            <?=__('More details'); ?>
        </a>
        <a href="#" class="hide-trigger hide-js" style="display: none" data-mage-init='{"showHideList":
            {
                "position":"<?= $_shown_items; ?>",
                "childElement":"p",
                "effect":"hide"
            }}'>
            <?=__('Collapse'); ?>
        </a>
    <?php endif; ?>
</div>
<?php endif; ?>
