<?php
/**
 * AutoBase default Catalog product view details template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php
            $detailedInfoGroup = ["product.attributes", "product.info.description"];
            ?>
            <div class="product items heading">
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>">
                    <a class="data switch"
                       href="#<?= $block->escapeUrl($alias); ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>-title">
                        <?= /* @noEscape */ $label; ?>
                    </a>
                </div>
            <?php endforeach;?>
            </div>
            <div class="product items content">
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                $alias = $layout->getElementAlias($name);
                ?>
                <div class="data item content"
                      id="<?= $block->escapeHtmlAttr($alias); ?>" >
                    <?= /* @noEscape */ $html; ?>
                </div>
            <?php endforeach;?>
            </div>
        </div>
    </div>
<?php endif; ?>
